### ISSUE TITLE
Possibly wrong filter ?

### ISSUE THREAD

**Issue by david-jankoski** [gadenbuie/mynorfolk-dash#2]
Hi Garrick, first of all i would like to say big thank you for putting this great example of targets + Quarto dash together, I have been looking at it for the past week and learned a ton from you - so thank you for making this publicly available.

I have one question / wonder - could it be that the `between` date filter [here](https://github.com/gadenbuie/mynorfolk-dash/blob/main/R/stats_today.R#L6) is not doing what it should be doing ? You called the variable `opened_yesterday` but the between filter would give you everything that is `yesterday <= x <= today` - so effectively also giving you tickets that were opened today.  
If i understood your intent correctly - the filter should be `between(creation_date, yesterday, yesterday)`.  

It's nothing big or important it is just to check my understanding of your code.
Thank you again, all the best and keep up the great work.

**Comment by gadenbuie** [comment]
Hi @david-jankoski, thanks for the question and I'm glad to hear that sharing the dashboard code has been helpful!

Here's the section of code you highlighted:

https://github.com/gadenbuie/mynorfolk-dash/blob/64b06931e01ff3c85fba1e6a64c4a8a1ea26b4a7/R/stats_today.R#L5-L6

In this case, IIRC, `today` is midnight of the current day, or `2024-03-13 00:00:00` as I write this. And `yesterday` is midnight of the day before, or `2024-03-12 00:00:00`. It's hard to tell from the code that the `today` and `yesterday` include time and aren't just dates (although if `creation_date` and `yesterday` were dates without time information I would just compare them directly like `creation_date == yesterday`).

From reading my code again I think it's doing what I expect -- finding tickets that were opened between midnight yesterday and midnight today, or essentially tickets opened yesterday. But I haven't run the code in a bit and the data may have shifted.

**Comment by david-jankoski** [comment]
ahhh i see - sorry it is my misunderstanding, i _thought_ that this part sets the `today, yesterday` variables which made me believe they are dates.  
https://github.com/gadenbuie/mynorfolk-dash/blob/main/_targets.R#L27-L29

thanks again for putting this together, i really liked and learned a lot from the way you used `targets` ⭐

**Comment by gadenbuie** [comment]
Thanks! And yeah, I can totally understand your reading of the code. In this code

```r
floor_date(max(norfolk$creation_date), unit = "day")
```

`floor_date()` rolls back `max(norfolk$creation_date)` to the nearest day boundary, but it keeps it as a datetime object. `floor_date()` is a `lubridate` favorite of mine 🥇 it's great for finding the nearest previous hour or week or month, etc.
